### ISSUE TITLE
Program failed to run

### ISSUE THREAD

**Issue by YoungSureshine** [plantonsanti/PartialMatchingVarifolds#1]
Dear author, I have a little problem when I run this code. "ImportError: cannot import name 'kernel_product' ".I suspect there is something wrong with my version (python=3.6 numpy=1.19, torch=1.10, cuda=11.2, gcc=7.5.0), can you share me the version that ran successfully, thanks very much.

**Comment by plantonsanti** [comment]
Thank you for your feedback, 
I have removed the imports that were causing you problems, I hope this has resolved the issue. I think it comes from the version of pykeops, I had a code in which I tried to import a deprecated module !
Best

**Comment by YoungSureshine** [comment]
Thank you for your reply, it's my honor. Thank you again for your contribution!


Best wish
On 4/29/2022 ***@***.***> wrote：

Thank you for your feedback,
I have removed the imports that were causing you problems, I hope this has resolved the issue. I think it comes from the version of pykeops, I had a code in which I tried to import a deprecated module !
Best
